### ISSUE TITLE
Full text search does not work

### ISSUE THREAD

**Issue by callmephilip** [AnswerDotAI/sqlite-minutils#14]
I am not able to use full-text search functionality at the moment. As far as I can tell, the issue coming from [detect_fts](https://github.com/simonw/sqlite-utils/blob/main/sqlite_utils/db.py#L2521-L2546) which returns `None`.

There is a [PR](https://github.com/AnswerDotAI/sqlite-minutils/pull/12) demonstrating the issue

**Comment by jph00** [comment]
FTS isn't part of this library. Use sqlite-utils for that. (It's one of the reasons this is "min")
